In [1]:
import pandas as pd
import json

with open('dataset-telecon.json') as f:
    json_bruto = json.load(f)

dados_normalizados = pd.json_normalize(json_bruto)

idx = dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].index

dados_normalizados.loc[idx,'conta.cobranca.Total'] = dados_normalizados.loc[idx,'conta.cobranca.mensal'] * 24
dados_normalizados.loc[idx,'cliente.tempo_servico'] = 24
dados_normalizados['conta.cobranca.Total'] = dados_normalizados['conta.cobranca.Total'].astype(float)
dados_sem_vazio = dados_normalizados[dados_normalizados['Churn'] != ''].copy()
dados_sem_vazio.reset_index(drop=True, inplace=True)

In [2]:
dados_sem_vazio.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7113     True
7114     True
7115     True
7116     True
7117     True
Length: 7118, dtype: bool

In [3]:
dados_sem_vazio.duplicated().sum()

75

In [4]:
filtro_duplicadas = dados_sem_vazio.duplicated()
filtro_duplicadas

0       False
1       False
2       False
3       False
4       False
        ...
7113     True
7114     True
7115     True
7116     True
7117     True
Length: 7118, dtype: bool

In [5]:
dados_sem_vazio[filtro_duplicadas]

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
7043,0675-NCDYU,nao,feminino,0,sim,sim,72.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,cartao de credito (automatico),116.40,8543.25
7044,6754-LZUKA,nao,masculino,0,sim,nao,61.0,sim,sim,DSL,...,sim,sim,nao,sim,sim,dois anos,nao,transferencia bancaria (automatica),80.90,4932.50
7045,2192-CKRLV,nao,feminino,0,sim,nao,72.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,dois anos,sim,cheque eletronico,49.20,3580.95
7046,9170-ARBTB,nao,feminino,0,sim,sim,52.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),19.60,1012.40
7047,0447-BEMNG,sim,feminino,0,sim,nao,48.0,nao,sem servico de telefone,DSL,...,nao,sim,nao,nao,sim,mes a mes,sim,transferencia bancaria (automatica),45.30,2145.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7113,5792-JALQC,nao,feminino,1,nao,nao,52.0,sim,sim,DSL,...,nao,sim,nao,nao,nao,dois anos,nao,transferencia bancaria (automatica),59.85,3103.25
7114,5172-RKOCB,nao,masculino,0,sim,nao,72.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,dois anos,sim,cartao de credito (automatico),108.95,7875.00
7115,1934-MKPXS,nao,masculino,0,sim,sim,33.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cartao de credito (automatico),20.10,620.55
7116,5959-BELXA,sim,masculino,1,nao,nao,32.0,sim,sim,fibra otica,...,nao,nao,nao,sim,sim,mes a mes,sim,cartao de credito (automatico),96.15,3019.25
7117,4452-QIIEB,nao,masculino,0,nao,nao,7.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,mes a mes,nao,cheque pelo correio,43.90,278.40

In [6]:
dados_sem_vazio.drop_duplicates(inplace=True)

In [7]:
dados_sem_vazio.duplicated().sum()

0

In [8]:
dados_sem_vazio.isna()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
dados_sem_vazio.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             8
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

In [10]:
dados_sem_vazio.isna().sum().sum()

114

In [11]:
dados_sem_vazio[dados_sem_vazio.isna().any(axis=1)]

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
9,0016-QLJIS,nao,feminino,0,sim,sim,NaN,sim,sim,DSL,...,sim,sim,sim,sim,sim,dois anos,sim,cheque pelo correio,90.45,5957.90
176,0282-NVSJS,nao,feminino,1,sim,sim,NaN,nao,sem servico de telefone,DSL,...,nao,nao,sim,nao,nao,mes a mes,sim,cheque pelo correio,29.30,355.90
181,0295-QVKPB,nao,masculino,0,nao,nao,NaN,sim,nao,DSL,...,nao,sim,sim,sim,nao,mes a mes,sim,cartao de credito (automatico),63.95,318.10
437,0639-TSIQW,sim,feminino,0,nao,nao,67.0,sim,sim,fibra otica,...,sim,sim,nao,sim,nao,None,None,cartao de credito (automatico),NaN,6886.25
751,1095-WGNGG,nao,feminino,0,sim,nao,NaN,sim,sim,fibra otica,...,sim,nao,nao,sim,sim,dois anos,sim,transferencia bancaria (automatica),101.05,5971.25
963,1396-QWFBJ,sim,feminino,0,sim,sim,21.0,sim,nao,fibra otica,...,sim,nao,nao,nao,nao,None,sim,None,NaN,1565.70
1604,2333-KWEWW,nao,masculino,0,nao,nao,18.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,nao,None,20.05,NaN
1605,2335-GSODA,nao,masculino,0,nao,sim,23.0,nao,sem servico de telefone,DSL,...,nao,sim,sim,nao,nao,None,nao,None,NaN,NaN
1606,2338-BQEZT,nao,feminino,0,nao,nao,55.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,cartao de credito (automatico),NaN,NaN
1608,2344-JMOGN,sim,masculino,0,sim,nao,9.0,sim,nao,fibra otica,...,sim,sim,sim,sim,nao,mes a mes,None,cheque pelo correio,NaN,890.60
2036,2931-FSOHN,nao,masculino,1,nao,nao,13.0,sim,nao,DSL,...,sim,nao,nao,sim,nao,mes a mes,sim,None,59.90,788.35
2037,2931-SVLTV,nao,masculino,0,sim,sim,40.0,sim,sim,fibra otica,...,sim,nao,sim,sim,sim,None,None,None,NaN,NaN
2039,2931-XIQBR,nao,feminino,0,sim,sim,50.0,sim,nao,fibra otica,...,nao,sim,sim,sim,sim,None,None,cheque pelo correio,103.05,5153.50
3523,4994-OBRSZ,nao,masculino,0,nao,sim,NaN,sim,nao,DSL,...,sim,sim,sim,nao,sim,dois anos,nao,transferencia bancaria (automatica),76.10,1054.80
4712,6637-KYRCV,nao,feminino,0,sim,sim,5.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,nao,nao,None,None,None,NaN,NaN
4716,6646-QVXLR,sim,masculino,1,sim,nao,62.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,cheque eletronico,NaN,NaN
4718,6647-ZEDXT,nao,feminino,0,nao,nao,30.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,nao,None,110.45,3327.05
4721,6650-VJONK,nao,masculino,0,nao,nao,1.0,sim,nao,DSL,...,nao,nao,nao,nao,nao,None,sim,transferencia bancaria (automatica),NaN,NaN
4725,6653-CBBOM,sim,feminino,0,nao,nao,1.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,sim,None,70.30,70.30
4728,6656-GULJQ,nao,masculino,0,sim,sim,72.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,cartao de credito (automatico),83.55,NaN
4731,6661-HBGWL,sim,feminino,1,nao,nao,42.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.75,NaN
4733,6664-FPDAC,sim,feminino,1,nao,nao,56.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,sim,cheque eletronico,NaN,NaN
4738,6680-NENYN,sim,feminino,0,nao,nao,43.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,None,sim,None,104.60,4759.85
4740,6681-ZSEXG,nao,masculino,0,sim,nao,56.0,sim,sim,DSL,...,sim,sim,nao,nao,nao,dois anos,nao,None,59.50,3389.25
4745,6685-XSHHU,nao,masculino,0,sim,sim,60.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,None,None,20.95,NaN
4749,6689-TCZHQ,sim,feminino,1,nao,nao,5.0,sim,nao,fibra otica,...,nao,nao,nao,nao,sim,mes a mes,None,None,78.95,378.40
4751,6691-CCIHA,nao,feminino,0,sim,nao,62.0,sim,sim,DSL,...,sim,nao,sim,sim,sim,None,sim,None,84.95,5150.55
4755,6693-FRIRW,nao,masculino,0,nao,nao,18.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,None,nao,None,NaN,NaN
4762,6702-OHFWR,sim,masculino,1,nao,nao,1.0,nao,sem servico de telefone,DSL,...,sim,sim,nao,nao,sim,None,None,None,43.30,43.30
5273,7435-ZNUYY,nao,masculino,0,nao,nao,NaN,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,cheque pelo correio,20.60,116.60
5276,7445-WMRBW,nao,feminino,0,nao,nao,NaN,sim,sim,DSL,...,sim,sim,sim,sim,nao,um ano,sim,transferencia bancaria (automatica),73.85,3581.40
5396,7606-BPHHN,nao,masculino,0,nao,nao,72.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,sim,cartao de credito (automatico),19.80,1468.75
5397,7607-QKKTJ,nao,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,nao,nao,sim,None,None,None,NaN,4368.85
5402,7611-YKYTC,nao,masculino,0,sim,sim,22.0,sim,nao,fibra otica,...,nao,nao,nao,nao,nao,None,nao,transferencia bancaria (automatica),NaN,NaN
5404,7614-QVWQL,sim,masculino,0,sim,sim,49.0,nao,sem servico de telefone,DSL,...,sim,nao,nao,sim,sim,None,None,None,NaN,NaN
5410,7622-FWGEW,nao,masculino,1,sim,nao,56.0,sim,nao,DSL,...,sim,sim,sim,sim,sim,None,sim,None,NaN,4824.45
5412,7623-HKYRK,nao,masculino,0,nao,sim,6.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.70,111.65
5415,7627-JKIAZ,sim,feminino,0,sim,nao,37.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,None,78.95,2839.65
6007,8480-PPONV,nao,masculino,0,sim,sim,62.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,None,None,transferencia bancaria (automatica),NaN,7159.05
6134,8690-UPCZI,nao,masculino,0,sim,sim,NaN,sim,sim,DSL,...,nao,nao,sim,sim,nao,um ano,nao,transferencia bancaria (automatica),69.05,1958.45
6181,8748-HFWBO,nao,masculino,0,sim,sim,19.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,None,None,None,19.90,357.70
6652,9465-RWMXL,sim,masculino,0,sim,nao,32.0,sim,sim,fibra otica,...,nao,sim,nao,nao,nao,None,None,None,78.90,2447.95
6655,9470-RTWDV,nao,masculino,0,sim,sim,26.0,sim,sim,DSL,...,nao,sim,sim,sim,sim,None,None,None,82.00,2083.10
6656,9470-XCCEM,nao,masculino,0,sim,sim,35.0,sim,sim,fibra otica,...,sim,nao,nao,sim,nao,None,sim,None,89.65,3161.60

In [13]:
filtro = dados_sem_vazio['cliente.tempo_servico'].isna()

In [14]:
dados_sem_vazio[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

      cliente.tempo_servico  conta.cobranca.mensal  conta.cobranca.Total
9                       NaN                  90.45               5957.90
176                     NaN                  29.30                355.90
181                     NaN                  63.95                318.10
751                     NaN                 101.05               5971.25
3523                    NaN                  76.10               1054.80
5273                    NaN                  20.60                116.60
5276                    NaN                  73.85               3581.40
6134                    NaN                  69.05               1958.45

In [17]:
import numpy as np

dados_sem_vazio['cliente.tempo_servico'].fillna(
    np.ceil(
        dados_sem_vazio['conta.cobranca.Total'] / dados_sem_vazio['conta.cobranca.mensal']
    ), inplace=True
)

In [21]:
dados_sem_vazio.isna().sum()

id_cliente                        0
Churn                             0
cliente.genero                    0
cliente.idoso                     0
cliente.parceiro                  0
cliente.dependentes               0
cliente.tempo_servico             0
telefone.servico_telefone         0
telefone.varias_linhas            0
internet.servico_internet         0
internet.seguranca_online         0
internet.backup_online            0
internet.protecao_dispositivo     0
internet.suporte_tecnico          0
internet.tv_streaming             0
internet.filmes_streaming         0
conta.contrato                   31
conta.faturamente_eletronico     17
conta.metodo_pagamento           26
conta.cobranca.mensal            17
conta.cobranca.Total             15
dtype: int64

In [25]:
colunas_to_drop = ['conta.contrato','conta.faturamente_eletronico', 'conta.metodo_pagamento']

In [30]:
dados_sem_vazio[colunas_to_drop].isna().any(axis=1)

0        True
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [32]:
df_sem_nulos = dados_sem_vazio.dropna(subset=colunas_to_drop).copy()

In [34]:
df_sem_nulos.reset_index(inplace=True, drop=True)