In [1]:
import pandas as pd
import json
import seaborn as sns

with open('dataset-telecon.json') as f:
    json_bruto = json.load(f)

dados_normalizados = pd.json_normalize(json_bruto)

idx = dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].index

dados_normalizados.loc[idx,'conta.cobranca.Total'] = dados_normalizados.loc[idx,'conta.cobranca.mensal'] * 24
dados_normalizados.loc[idx,'cliente.tempo_servico'] = 24
dados_normalizados['conta.cobranca.Total'] = dados_normalizados['conta.cobranca.Total'].astype(float)
dados_sem_vazio = dados_normalizados[dados_normalizados['Churn'] != ''].copy()
dados_sem_vazio.reset_index(drop=True, inplace=True)

dados_sem_vazio.drop_duplicates(inplace=True)

In [2]:
filtro = dados_sem_vazio['cliente.tempo_servico'].isna()

dados_sem_vazio[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

import numpy as np

dados_sem_vazio['cliente.tempo_servico'].fillna(
    np.ceil(
        dados_sem_vazio['conta.cobranca.Total'] / dados_sem_vazio['conta.cobranca.mensal']
    ), inplace=True
)

colunas_to_drop = ['conta.contrato','conta.faturamente_eletronico', 'conta.metodo_pagamento']

df_sem_nulos = dados_sem_vazio.dropna(subset=colunas_to_drop).copy()

df_sem_nulos.reset_index(inplace=True, drop=True)

In [3]:
Q1 = df_sem_nulos['cliente.tempo_servico'].quantile(.25)

Q3 = df_sem_nulos['cliente.tempo_servico'].quantile(.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR

outliers_index = (df_sem_nulos['cliente.tempo_servico'] < limite_inferior) | (df_sem_nulos['cliente.tempo_servico'] > limite_superior)

In [4]:
df_sem_out = df_sem_nulos.copy()

df_sem_out.loc[outliers_index, 'cliente.tempo_servico'] = np.ceil(
    df_sem_out.loc[outliers_index, 'conta.cobranca.Total'] / df_sem_out.loc[outliers_index, 'conta.cobranca.mensal']
)

Q1 = df_sem_out['cliente.tempo_servico'].quantile(.25)

Q3 = df_sem_out['cliente.tempo_servico'].quantile(.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR

outliers_index = (df_sem_out['cliente.tempo_servico'] < limite_inferior) | (df_sem_out['cliente.tempo_servico'] > limite_superior) 

df_sem_out = df_sem_out[~outliers_index]

In [5]:
df_sem_id = df_sem_out.drop('id_cliente', axis=1).copy()
df_sem_id

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.90,542.40
1,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.90,280.85
2,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.00,1237.85
3,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.90,267.40
4,nao,feminino,0,nao,sim,9.0,sim,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,sim,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,nao,feminino,0,nao,nao,13.0,sim,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,nao,cheque pelo correio,55.15,742.90
7002,sim,masculino,0,sim,nao,22.0,sim,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,sim,cheque eletronico,85.10,1873.70
7003,nao,masculino,0,nao,nao,2.0,sim,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,sim,cheque pelo correio,50.30,92.75
7004,nao,masculino,0,sim,sim,67.0,sim,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,nao,cheque pelo correio,67.85,4627.65
7005,nao,masculino,0,sim,sim,63.0,nao,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,nao,cheque eletronico,59.00,3707.60

In [6]:
mapeamento = {
    'nao': 0,
    'sim': 1,
    'masculino': 0,
    'feminino': 1
}

In [7]:
for col in df_sem_id.columns:
    print(f"Coluna: {col}")
    print(df_sem_id[col].unique())
    print("-" * 30)

Coluna: Churn
['nao' 'sim']
------------------------------
Coluna: cliente.genero
['masculino' 'feminino']
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
['nao' 'sim']
------------------------------
Coluna: cliente.dependentes
['nao' 'sim']
------------------------------
Coluna: cliente.tempo_servico
[ 9.  4. 13.  3. 71. 63.  7. 66. 54. 72.  5. 56. 34.  1. 45. 50. 23. 55.
 26. 69. 37. 49. 67. 20. 43. 59. 12. 27.  2. 25. 29. 14. 35. 64. 39. 40.
 11.  6. 30. 70. 57. 58. 16. 32. 33. 10. 21. 61. 15. 44. 22. 24. 19. 47.
 62. 46. 52.  8. 60. 48. 28. 41. 53. 68. 31. 36. 17. 18. 65. 51. 38. 42.]
------------------------------
Coluna: telefone.servico_telefone
['sim' 'nao']
------------------------------
Coluna: telefone.varias_linhas
['sim' 'nao' 'sem servico de telefone']
------------------------------
Coluna: internet.servico_internet
['DSL' 'fibra otica' 'nao']
------------------------------
Coluna: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.backup_online
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.suporte_tecnico
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.tv_streaming
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.filmes_streaming
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: conta.contrato
['mes a mes' 'dois anos' 'um ano']
------------------------------
Coluna: conta.faturamente_eletronico
['nao' 'sim']
------------------------------
Coluna: conta.metodo_pagamento
['cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
------------------------------
Coluna: conta.cobranca.mensal
[59.9  73.9  98.   ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[ 542.4   280.85 1237.85 ...  742.9  4627.65 3707.6 ]
------------------------------

In [8]:
colunas = ['Churn', 'cliente.genero', 'cliente.parceiro', 'cliente.dependentes', 'telefone.servico_telefone', 'conta.faturamente_eletronico']

df_sem_id[colunas] = df_sem_id[colunas].replace(mapeamento)
df_sem_id

,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,internet.seguranca_online,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0,0,0,0,0,9.0,1,sim,DSL,nao,nao,nao,nao,nao,sim,mes a mes,0,cheque pelo correio,59.90,542.40
1,1,0,0,0,0,4.0,1,nao,fibra otica,nao,nao,sim,nao,nao,nao,mes a mes,1,cheque eletronico,73.90,280.85
2,1,0,1,1,0,13.0,1,nao,fibra otica,nao,sim,sim,nao,sim,sim,mes a mes,1,cheque eletronico,98.00,1237.85
3,1,1,1,1,0,3.0,1,nao,fibra otica,nao,nao,nao,sim,sim,nao,mes a mes,1,cheque pelo correio,83.90,267.40
4,0,1,0,0,1,9.0,1,nao,DSL,nao,nao,nao,sim,sim,sim,mes a mes,1,cartao de credito (automatico),69.40,571.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001,0,1,0,0,0,13.0,1,nao,DSL,sim,nao,nao,sim,nao,nao,um ano,0,cheque pelo correio,55.15,742.90
7002,1,0,0,1,0,22.0,1,sim,fibra otica,nao,nao,nao,nao,nao,sim,mes a mes,1,cheque eletronico,85.10,1873.70
7003,0,0,0,0,0,2.0,1,nao,DSL,nao,sim,nao,nao,nao,nao,mes a mes,1,cheque pelo correio,50.30,92.75
7004,0,0,0,1,1,67.0,1,nao,DSL,sim,nao,sim,sim,nao,sim,dois anos,0,cheque pelo correio,67.85,4627.65
7005,0,0,0,1,1,63.0,0,sem servico de telefone,DSL,sim,sim,sim,nao,sim,sim,dois anos,0,cheque eletronico,59.00,3707.60

In [10]:
s = pd.Series(list('abca'))
s

0    a
1    b
2    c
3    a
dtype: object

In [13]:
pd.get_dummies(s, dtype=int)

   a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [14]:
df_sem_id.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7002 entries, 0 to 7005
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Churn                          7002 non-null   int64
 1   cliente.genero                 7002 non-null   int64
 2   cliente.idoso                  7002 non-null   int64
 3   cliente.parceiro               7002 non-null   int64
 4   cliente.dependentes            7002 non-null   int64
 5   cliente.tempo_servico          7002 non-null   float64
 6   telefone.servico_telefone      7002 non-null   int64
 7   telefone.varias_linhas         7002 non-null   object
 8   internet.servico_internet      7002 non-null   object
 9   internet.seguranca_online      7002 non-null   object
 10  internet.backup_online         7002 non-null   object
 11  internet.protecao_dispositivo  7002 non-null   object
 12  internet.suporte_tecnico       7002 non-null   object
 13  internet.tv_streaming          7002 non-null   object
 14  internet.filmes_streaming      7002 non-null   object
 15  conta.contrato                 7002 non-null   object
 16  conta.faturamente_eletronico   7002 non-null   int64
 17  conta.metodo_pagamento         7002 non-null   object
 18  conta.cobranca.mensal          7002 non-null   float64
 19  conta.cobranca.Total           7002 non-null   float64
dtypes: float64(3), int64(7), object(10)
memory usage: 1.1+ MB

In [18]:
df_dummies = pd.get_dummies(df_sem_id, dtype=int).copy()

In [19]:
df_dummies.columns

Index(['Churn', 'cliente.genero', 'cliente.idoso', 'cliente.parceiro',
       'cliente.dependentes', 'cliente.tempo_servico',
       'telefone.servico_telefone', 'conta.faturamente_eletronico',
       'conta.cobranca.mensal', 'conta.cobranca.Total',
       'telefone.varias_linhas_nao',
       'telefone.varias_linhas_sem servico de telefone',
       'telefone.varias_linhas_sim', 'internet.servico_internet_DSL',
       'internet.servico_internet_fibra otica',
       'internet.servico_internet_nao', 'internet.seguranca_online_nao',
       'internet.seguranca_online_sem servico de internet',
       'internet.seguranca_online_sim', 'internet.backup_online_nao',
       'internet.backup_online_sem servico de internet',
       'internet.backup_online_sim', 'internet.protecao_dispositivo_nao',
       'internet.protecao_dispositivo_sem servico de internet',
       'internet.protecao_dispositivo_sim', 'internet.suporte_tecnico_nao',
       'internet.suporte_tecnico_sem servico de internet',
       'internet.suporte_tecnico_sim', 'internet.tv_streaming_nao',
       'internet.tv_streaming_sem servico de internet',
       'internet.tv_streaming_sim', 'internet.filmes_streaming_nao',
       'internet.filmes_streaming_sem servico de internet',
       'internet.filmes_streaming_sim', 'conta.contrato_dois anos',
       'conta.contrato_mes a mes', 'conta.contrato_um ano',
       'conta.metodo_pagamento_cartao de credito (automatico)',
       'conta.metodo_pagamento_cheque eletronico',
       'conta.metodo_pagamento_cheque pelo correio',
       'conta.metodo_pagamento_transferencia bancaria (automatica)'],
      dtype='object')